schemaVersion: "2.2"
description: "Setup website"
mainSteps:
  - action: "aws:runShellScript"
    name: "setup_website"  # <- Changed this to a valid name
    inputs:
      timeoutSeconds: '300'
      runCommand:
      - sudo apt update
      - sudo chown -R ubuntu:ubuntu /var/www/html
      - sudo chmod +x *.sh
      - git clone https://github.com/CloudbrokerAz/lens.git /tmp/website
      - sudo rm -rf /var/www/html/*
      - sudo cp -r /tmp/website/* /var/www/html/
      - sudo rm -rf /tmp/website
      - sudo rm -rf /var/www/html/.git
      - sed -i "s|<h2>The future has landed|<h2>${description} The future has landed|" /var/www/html/index.html
      